sudo: false
dist: trusty
language: node_js
node_js: node
addons:
  apt:
    packages:
      - google-chrome-stable
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
env:
  global:
    - secure: >-
        mBBiPIc2161EK7HWl8LkoaJF073cyvBaTLKx55nYiN/EKi1adx+JLN9j5frH4CvqB+0nmSum3ltC7ONQA+nqr4jq0qXc5s1cdAHDkKupxdUFrLBALaYVIHXRrJVr+Ew6y3EWX+8dUf9843j0ToGIFhAaRIYQ1X+X37rPJGbNi7UzvJPn8634tBvIt+cjQzaS8mFfXy3BbAfFS4Qm92DXekTBinJIuZbBJ8bxzgMi0PZ6bgWHJ8v5d/vdEEyYkM3zs995bgOPf/UWuUfR5akdIu07pgN7Z6ZgzIKus0r6zECmV6fvgyJWkoMXboM1MoWToti8n8P6k8V2QhQHkOYTP7Zea3PL9MJEO3txd7/9cujZ0EGIkYFZBgfRsxyJJgi+gphWgxEIy4AGoyHKjPlsj3pyXs1QoScjIVw4ecz9bNI9YLcKZbaRCSe5CcZeR0i/V0dFb35Cn+/AS59CbVGyLpXj2GDDseNe6L0cU2y2Xy6mIVR7djH/twLlsInc1Q+IICTBPOrO1vN8bu4wtDyT/R81tOQJdvYUwkBmqzTQjhNx4hmDiLB6vGQhpzkpcGKEyddFSxR3oxvdk2wNo73JZfyVjx+CMLr/s90wI67bGXJTykeOgoc/zbUS8JW6X/Uf7mgdKF9dlwMiegcbh7qcGcs1BoQnOXVAk7T1K6hwOFg=
    - secure: >-
        dzLD8Aj1A33H/nNBMr6AaW/1UN6/69iELDIuJbu+SRkkPLXAPaIo8OSL+Jb26SXhIYDZl1anIi46uROhCZxrE3M9WmEobsg0fmB1nweehKW27lgMkPm7YSyk9AwEqRmRb5GziZqBcR0bMWa8gifZ2F0bx2i7BLN+tkwgdVRifhW4u3fW3iKjJ246FOByrP/7pBVPgzSkLwasV2/nWWKTTw1gLZb13l9KwcfbdQccMP0s+awmtvF+5Rb1+U0/qidSto+0o34cF5dckCdYVFW3dwL7wG3Ak1kdWA1Jw1cvpOwKHqNu+n3O+yJ0nLoDCUcUPtsempBP/vDWHe9ZfT4I59khY/F4tgbP/DyAccYtp3xsZYjLlEs2LpYMstgYjR84V+D9DdXh6M8yvYtU+Oxm5EByD8hRtfEp5sl0fUMz2UBxWQobuzvdVZKyj7h1xEHSU9NDFEAoR0bR0aFxWzONgXuujugI3sOwS9JZ1JYya7CPJH4VoFyTy3FwkSqn/AI1tNZIhpeGe6AGY6RrpfxLG6HpP9U4m22PiuyPPT6Lws9gk9uBtpHymX1wCqVn734bpM54V8p6O1mIloFGsjpb2opTznyE6QB3C3QN1ddTq1nimjMXDmixoq/pvHeNmuw5DXoeScRYYIcO7O1MwirGUmjdyVg9SFWnN8k4NVDkDYY=
    - secure: >-
        GbD6B7t40HOtkrVr7ASyCnuikUF1y2UPi9x1CY3JtwKDP438WK0oIHK6G4m90zH5fkmxaJCcfOlS8WgO39fyTv7o638kly3Qaf6MoA76TF3RVonhDS7ccbZHycRh/eRE6oS00rVw/Q/wIOAIfVT8l8d7hj9MSq7qEYa8slNH9ThVr0sebCYQlqiJipoCr6VxBrvVAtYb5Ks+mNJqg4pkY0mr03OFE1CxHCojBlUXJ/eTWnShtA36fIQfkbhZ/3Gur5M9t/Q12f6MnY5bbdZIY9sgFGqT/ZxuZCzPUe0Cw0hCWBIFOtveSCn9SCyop7w0VN67Ig6IvX/RsqKWkCyQoQy2PoA3KPun3lD93mt3jUOjHVA0w61EEjyvfOYSNr/1Ef8Q1K/meHb3UsyC4vn+NgU40ihRjXvjODxGrouU7K9YlpPnQVQiDOM6ieBUTOd+BU7Nj6j21g3m8BZazE6yoKys6nnZq7E/dXjG03lcQC5DSuwxYwfLAMdtKJ00B/L74kmYsQfnoqCcAJj5F+KaKq2MfIQHqw4A0McIDLJEs8IDPNoDmXmN3egSUgwN9rg9TVOGQHtZ/FWAgMjKOp6J2PLUPq4i86D9wBOsU9IMYMoy+p6iWNIClKDA6oFIXKdylywzh4k3yNUBYS9kxGdmnQQseCQlEEV8bQJJDWq4I/Y=
